### ISSUE TITLE
Mol* not showing available minimized structure on carbohydrate builder download page

### ISSUE THREAD

**Issue by gitoliver** [GLYCAM-Web/website#265]
Bacterial builder we get this feedback from Ferran about  Mol*
At the bottom it says "Minimized? No", and even when I
run AAT alone, it still says "Minimized? No", even though this time I
get "Simulation finished normally". 

This is likely a general error, and the report was some months ago so may even be fixed already by Dan.

**Comment by gitoliver** [comment]
Yes it's a generic issue. I see it on test and actual:
https://jam.dev/c/e6131e5f-a560-4766-94d4-01531a35772b
https://jam.dev/c/6c7e58b8-e3eb-49c3-84f5-476cb2bd1c50
I guess that it will show the minimized version automatically if it's available when it checks for it, but if it's not available then it doesn't check again once the minimization is complete. Manually clicking the button works, but users will be confused by a status of "Everything finished" and Mol* saying: minimized: No.

**Comment by danwentworthart** [comment]
I believe I have fixed this issue. Solution is working when I test on LiveTest.

**Comment by pallabkumarborah** [comment]
Problem is back again. Project Status: Project completed. Manually clicking the 'Download minimized structure' button did not work.

**Comment by Lachele** [comment]
We are having site-wide issues ATM. We are working on it. I'm headed to generate a flag saying so. Thanks for letting us know!
